apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: kepehyoyo/payment-gateway
          env:       
            - name: MONGO_URI
              value: 'mongodb://payment-gateway-mongo-srv:27017/payment-gateway'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-srv
spec:
  selector:
    app: payment-gateway
  ports:
    - name: payment-gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
