apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode
  template:
    metadata:
      labels:
        app: qrcode
    spec:
      containers:
        - name: qrcode
          image: kepehyoyo/qrcode
          env:
            - name: MONGO_URI
              value: 'mongodb://qrcode-mongo-srv:27017/qrcode'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: qrcode-srv
spec:
  selector:
    app: qrcode
  ports:
    - name: qrcode
      protocol: TCP
      port: 3000
      targetPort: 3000
